src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class FrontController extends AbstractController
{
    /**
     * @Route("/accueil", name="accueil")
     */
    public function index()
    {
        return $this->render('front/index.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    /**
     * @Route("/accueil/abonnement", name="abonnement")
     */
    public function abonnement()
    {
        return $this->render('abonnement.html.twig');
    }
}

templates/front/includes/footer.html.twig
<footer class="site-footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 mb-5 mb-lg-0">
				<div class="row mb-5">
					<div class="col-12">
						<h3 class="footer-heading mb-4">À Propos</h3>
						<p>Petit Yogi c'est une application web et mobile, ludique, pour pratiquer le Yoga avec toute la famille</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4"></div>
			<div class="col-lg-4 mb-5 mb-lg-0">

				<div class="mb-5">
					<h3 class="footer-heading mb-2">Recevoir la Newsletter</h3>
					<p>Des mots doux et des surprises chaque mois, dans votre boite mail</p>

					<form action="#" method="post" class="form-subscribe">
						<div class="input-group mb-3">
							<input type="text" class="form-control border-white text-white bg-transparent" placeholder="Enter Email" aria-label="Votre Email" aria-describedby="button-addon2">
							<div class="input-group-append">
								<button class="btn btn-primary" type="button" id="button-addon2">Envoyer</button>
							</div>
						</div>
					</form>
				</div>
			</div>

		</div>
		<div class="row pt-5 mt-5 text-center">
			<div class="col-md-12">
				<p>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;<script>
						document.write(new Date().getFullYear());
					</script>
					Tous droits réservés | Ce template provient de
					<a href="https://colorlib.com" target="_blank">Colorlib</a>
					et modifié avec
					<i class="icon-heart text-danger" aria-hidden="true"></i>
					par
					<a href="#" target="_blank">Mathilde Moreau</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
			</div>

		</div>
	</div>
</footer>

templates/front/includes/header.html.twig
<div id="overlayer"></div>
<div class="loader">
	<div class="spinner-border text-primary" role="status">
		<span class="sr-only">Loading...</span>
	</div>
</div>

<div class="site-wrap">

	<div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close mt-3">
				<span class="icon-close2 js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>
	<!-- .site-mobile-menu -->

	<div class="site-navbar site-navbar-target js-sticky-header">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-2">
					<h1 class="my-0 site-logo">
						<a href="{{ path ('accueil') }}">Petit Yogi</a>
					</h1>
				</div>
				<div class="col-10">
					<nav class="site-navigation text-right" role="navigation">
						<div class="container">
							<div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3">
								<a href="#" class="site-menu-toggle js-menu-toggle text-white">
									<span class="icon-menu h3"></span>
								</a>
							</div>

							<ul class="site-menu main-menu js-clone-nav d-none d-lg-block">
								<li>
									<a href="#qui-nous-sommes" class="nav-link">Qui nous sommes</a>
								</li>
								<li class="has-children">
									<a href="#" class="nav-link">Notre Offre</a>
									<ul class="dropdown arrow-top">
										<li>
											<a href="#notre-offre" class="nav-link">Abonnement</a>
										</li>
										<li>
											<a href="#créer un fichier twig ici" class="nav-link">FAQ</a>
										</li>
									</ul>
								</li>
								<li>
									<a href="#" data-toggle="modal" data-target="#connexionModal" class="nav-link">Connexion | Inscription</a>
									{% if app.user.username is defined %}
										logged: {{ app.user.username }} 
									{% endif %}		
								
								</li>
								<li>
									<a href="#contactez-nous" class="nav-link">Contact</a>
								</li>
							</ul>
						</div>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal LOGIN et REGISTER -->
<div class="modal fade" id="connexionModal" tabindex="-1" role="dialog" aria-labelledby="Connexion" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="Connexion">Connexion</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Fermer-croix">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">

				<!-- include de la vue du login  -->
				{% include "security/login.html.twig" %}
				
				<!-- <form>
					<div class="form-group">
						<label for="exampleInputEmail1">Votre Email</label>
						<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"> -->
						<!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
					<!-- </div>
					<div class="form-group">
						<label for="exampleInputPassword1">Mot de passe</label>
						<input type="password" class="form-control" id="exampleInputPassword1">
					</div>
					<button type="submit" class="btn btn-primary">Go !</button> -->
					<!-- inserer ici if else pr connexion-->
				<!-- </form> -->
			</div>
			<div class="modal-footer">
			<p>Pas encore de Compte ? Inscrivez-vous !</p>

			<!-- include de l'action register (seulement pour test) 
			qui affiche et traite le form d'inscription 
			Attention car pour gérer les erreurs d'inscription il faudra faire pas mal de changements! -->
	
			{{ render (controller (
				'App\\Controller\\RegistrationController::register' 
				))
			}}  
		    
			<!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">S'inscrire</button> -->
			</div>
		</div>
	</div>
</div>